version: "3.1"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: "sh -c"
    command:
      - "npm run start"
    volumes:
      - ./src:/app/src
      - ./nest-cli.json:/app/nest-cli.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
    hostname: "app"
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      JWT_SECRET: "${JWT_SECRET}"
      OWNER_EMAIL: "${OWNER_EMAIL}"
      OWNER_PASSWORD: "${OWNER_PASSWORD}"

  postgres:
    image: "postgres:14-alpine"
    hostname: "postgres"
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
